[package]
name = "bfe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.3"
bcrypt = "0.15.0"
bcrypt-small = "0.1.1"
crypto = "0.5.1"
engine = "0.0.0"
